# Use the official PowerShell image as a base
FROM mcr.microsoft.com/dotnet/sdk:9.0-preview-bookworm-slim

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Set the default user. Omit if you want to keep the default as root.
# USER vscode