name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.vscode/**'
      - '.devcontainer/**'
      - 'tools/**'
      - 'README.md'
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.vscode/**'
      - '.devcontainer/**'
      - 'tools/**'
      - 'README.md'
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: write    # Required for creating releases
  packages: write    # Required for publishing packages

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
    
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Build and Pack
        run: ./build.ps1 -Configuration Release -Version '${{ steps.gitversion.outputs.semVer }}'
        shell: pwsh
      
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./PSFlurl/PSFlurl*.nupkg
          retention-days: 5

  test:
    name: Test (${{ matrix.os }})
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: artifacts

      - name: Extract Module
        shell: pwsh
        run: |
          Get-ChildItem -File -Recurse | Where-Object { $_.Extension -eq '.nupkg' } | Select-Object -ExpandProperty FullName
          $nupkg = Get-ChildItem ./artifacts/*.nupkg
          $extractPath = Join-Path ./artifacts 'PSFlurl'
          Expand-Archive -Path $nupkg -DestinationPath $extractPath -Force
          Write-Host "Extracted module to: $extractPath"
      
      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          
      - name: Run Tests
        shell: pwsh
        run: |
          Import-Module Pester -Force -PassThru
          Import-Module ./artifacts/PSFlurl/PSFlurl.psd1 -Force -Verbose
          $config = [PesterConfiguration]::Default
          $config.Run.Path = './tests/PSFlurl.Tests.ps1'
          $config.Output.Verbosity = 'Detailed'
          $config.Run.PassThru = $true
          Invoke-Pester -Configuration $config
          
  publish:
    name: Publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: windows-latest
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: artifacts

      - name: Create Release
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $nupkg = Get-ChildItem ./artifacts/PSFlurl.*.nupkg
          $version = $nupkg.BaseName -replace 'PSFlurl\.'
          Write-Host "Version: $version"
          $secureToken = $env:GH_TOKEN | ConvertTo-SecureString -AsPlainText -Force
          $releaseParams = @{
              Authentication = 'Bearer'
              Body           = @{
                  tag_name   = "v$version"
                  name       = "v$version"
                  body       = "Release v$version"
                  draft      = $false
                  prerelease = $false
              } | ConvertTo-Json
              ContentType    = 'application/json'
              Headers        = @{ Accept = 'application/vnd.github.v3+json' }
              Method         = 'POST'
              Token          = $secureToken
              Uri            = 'https://api.github.com/repos/${{ github.repository }}/releases'
          }
          $release = Invoke-RestMethod @releaseParams
          $release
          # Upload asset
          $assetParams = @{
              Authentication = 'Bearer'
              ContentType    = 'application/octet-stream'
              Headers        = @{ Accept = 'application/vnd.github.v3+json' }
              InFile         = $nupkg.FullName
              Method         = 'POST'
              Token          = $secureToken
              Uri            = $release.upload_url -replace '\{\?.*\}',"?name=$($nupkg.Name)"
          }
          Invoke-RestMethod @assetParams

      - name: Publish to PowerShell Gallery
        env:
          NUGET_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
        run: |
          $nupkg = Get-ChildItem ./artifacts/PSFlurl*.nupkg
          $extractPath = Join-Path ./artifacts 'PSFlurl'
          Expand-Archive -Path $nupkg -DestinationPath $extractPath -Force
          Get-ChildItem -Path $extractPath -Recurse -File |
              Where-Object { $_.Extension -eq '.xml' } |
              Remove-Item -Force
          Write-Host "Extracted module to: $extractPath"
          Write-Host "Publishing package: $($nupkg.FullName)"
          Publish-Module -NuGetApiKey ${{ env.NUGET_KEY }} -Path $extractPath -Repository PSGallery -Force -Verbose
        shell: pwsh
