name: Pull Request

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Module
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Build Module
        run: |
          dotnet restore
          dotnet publish --configuration Release --output ./artifacts
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Flurl
          path: ./artifacts/*.*

  test:
    needs: build
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Flurl
          path: Flurl
      
      - name: Setup PowerShell
        uses: pwshrc/actions-install-powershell@v1
        with:
          pwsh-version: latest
      
      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Import-Module Pester -Force -PassThru
      
      - name: Run Pester Tests
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}/Flurl/Flurl.psd1 -Force -Verbose
          $config = [PesterConfiguration]::Default
          $config.Run.Path = "${{ github.workspace }}/Flurl/Flurl.Tests.ps1"
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config -PassThru