name: Publish

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Release Info
        env:
          RELEASE_INFO: ${{ toJSON(github.event.release) }}
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Full Release Info: $RELEASE_INFO"
    
      - name: Get Tag SHA
        id: tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=$(gh api repos/${{ github.repository }}/git/refs/tags/${{ github.event.release.tag_name }} --jq .object.sha)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Tag ${{ github.event.release.tag_name }} points to: $SHA"

      - name: Download Artifact from CI Run
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ steps.tag.outputs.sha }}
          name: nupkg
          path: artifacts

      - name: Publish to PowerShell Gallery
        env:
          NUGET_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_KEY --source https://www.powershellgallery.com/api/v2/package