name: Publish

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
    
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Build and Pack
        run: |
          dotnet restore src/Flurl.Cmdlets/Flurl.Cmdlets.csproj
          dotnet build src/Flurl.Cmdlets/Flurl.Cmdlets.csproj --configuration Release -p:Version=${{ steps.gitversion.outputs.semVer }}
          dotnet pack src/Flurl.Cmdlets/Flurl.Cmdlets.csproj --configuration Release --output ./artifacts -p:Version=${{ steps.gitversion.outputs.semVer }}
      
      - name: Publish to PowerShell Gallery
        env:
          NUGET_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key $env:NUGET_KEY --source https://www.powershellgallery.com/api/v2/package